AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Task Definition with ECR Docker Image

Parameters:
  # ApplicationName:
  #   Description: Name of application the ecs 2.0 env is associated with
  #   Type: String
  #   MinLength: 3
  #   Default: arch
  AssignPublicIp:
    Type: String
    AllowedValues:
    - ENABLED
    - DISABLED
    Default: ENABLED
  # Contact:
  #   Description: First and last name of contact
  #   Type: String
  #   Default: First Last
  # ContainerName:
  #   Type: String
  #   Description: Name of the container used to push Docker image into the ECR repository
  #   Default: hello-world-python
  # CostCenter:
  #   Description: Cost Center
  #   Type: String
  #   Default: "12345"
  # Department:
  #   Description: Department Name
  #   Type: String
  #   Default: Department
  # EcrRepositoryName:
  #   Type: String
  #   Description: Name of the ECR repository where the Docker image is stored
  #   Default: test-adam
  EcrImageTag:
    Type: String
    Description: Tag of the Docker image in the ECR repository
    Default: latest
  # ECSCluster:
  #   Type: String
  #   Description: ECS Cluster
  #   Default: test-adam
  Environment:
    Description: Type of Environment
    AllowedPattern: "[a-z0-9]*"
    Type: String
    AllowedValues:
    - dev
    - test
    - staging
    - prod
    - dr
    - sbx
    Default: sbx
  LaunchType:
    Type: String
    Description: Choose Fargate or EC2
    AllowedValues:
    - FARGATE
    - EC2
    Default: FARGATE
  Purpose:
    Description: Purpose of ecs instance
    Type: String
    Default: test
    # SGOS:
    #   Description: OS of StackSet management SG
    #   Type: String
    #   AllowedValues:
    #     - linux
    #     - windows
    #     - none

Resources:
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
      - FARGATE
      NetworkMode: awsvpc
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !GetAtt ECSTaskRole.Arn
      ContainerDefinitions:
      - Name: mycontainer
        Image: 490774640821.dkr.ecr.eu-west-1.amazonaws.com/kudzi-repo:latest
        Memory: 512 # Memory at the container level is optional, but it can be specified separately from the task level
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Ref LogGroup
            awslogs-region: !Ref AWS::Region
            awslogs-stream-prefix: !Ref AWS::StackName

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: FargateCluster
      ServiceName: !Sub ${AWS::StackName}-service
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: !Ref LaunchType
      LoadBalancers:
      - ContainerName: !Sub ${AWS::StackName}
        ContainerPort: '80'
        LoadBalancerName: !Ref elb
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: !Ref AssignPublicIp # Keep DISABLED if not using public IP
          Subnets:
          - subnet-6262b405
          - subnet-c912b980
          - subnet-930dd1da
          SecurityGroups:
          - sg-4d247c36
          #  - Fn::ImportValue: !Sub "${SGOS}-mgmt-${Environment}-sg-id"

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${AWS::StackName}

  elb:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      LoadBalancerName: !Sub ${AWS::StackName}-2023
      Listeners:
      - InstancePort: '80'
        LoadBalancerPort: '80'
        Protocol: HTTP
      Subnets:
      - subnet-6262b405
      - subnet-c912b980
      # - subnet-930dd1da

# Outputs:
#   ECSRoleARN:
#     Description: IAM Role ARN for ECS tasks
#     Value: !GetAtt ECSTaskRole.Arn
